# Numpy: Package for Multidimensional array
### Vector(1d)
### Matrix (2d or 1d)

In [1]:
import numpy as np
## numpy used whenever we have to deal with numbers, linear algebra, matrix etc..
list=[1,2,3,4,5,500]
sample_list= np.array(list)
sample_list

array([  1,   2,   3,   4,   5, 500])

### Create an Array

In [3]:
import numpy as np 
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])  #this will arrange in elements in ascending order
arr

array([1, 2, 3])

In [2]:
list_of_lists= ([1,2,3], [4,5,6], [7,8,9])
np.array(list_of_lists)   #This is how we get an matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(5,28)  #list or array without step size upto n-1 i.e 28-1 =27 will be printed

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [5]:
np.arange(5,35,6) #here we will get step size of 6 i.e 5, 11, 17....29
                  #Note: 35 will not be printed as it is n-1 i.e 35-1=34..

array([ 5, 11, 17, 23, 29])

In [6]:
np.arange(5,36,6)

array([ 5, 11, 17, 23, 29, 35])

In [7]:
np.arange(5,35,8)

array([ 5, 13, 21, 29])

In [9]:
np.zeros(6)            #zeros are in by defualt float type

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(5,dtype=int)   #ones in integer type

array([1, 1, 1, 1, 1])

In [13]:
np.ones((2,5), dtype=int) # 2 specifes rows and 5 specifies columns both in integer type

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.linspace(0,20,10) # range from 0 to 20 with 10 equal parts

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [14]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [15]:
np.eye(5, dtype=int)  #identity matrix 5x5 with integer values

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [16]:
np.eye(5)   #identity matrix 5x5 with by defualt float values

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(2,4) #Create an array of the given shape and populate it with
                    #random samples from a uniform distribution
                    #over ``[0, 1)``.

array([[0.44813802, 0.3419516 , 0.7806091 , 0.93765577],
       [0.14441288, 0.34545263, 0.76622027, 0.24814688]])

In [18]:
np.random.randn(2,4) #return random values that are +ve or/and -ve
#Return a sample (or samples) from the "standard normal" distribution

array([[ 1.66130837, -0.72043849,  0.30318936, -0.3067371 ],
       [-1.30647319, -0.70908807,  0.6078156 , -0.68413547]])

In [20]:
np.random.rand(2,5)

array([[0.28881784, 0.81051655, 0.36114682, 0.92069628, 0.48223718],
       [0.38999531, 0.31610835, 0.62603482, 0.25210877, 0.62880375]])

In [22]:
np.random.randint(0,10,15)   #random values with integer type
                            #0 starting value, 10-1=9 last value, count of values =15

array([9, 9, 1, 9, 8, 5, 3, 6, 3, 4, 5, 7, 7, 9, 5])

In [42]:
np.random.randint(10,100,16)

array([34, 40, 41, 85, 74, 40, 82, 83, 58, 57, 15, 43, 65, 54, 79, 10])

In [41]:
sample_array=np.arange(2,40)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39])

In [40]:
sample_array=np.arange(2,40,3)
sample_array

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38])

In [26]:
sample_array.min()

2

In [28]:
sample_array.argmin() #index of minimum value

0

In [39]:
rand_array=np.random.randint(0,10,6)
rand_array

array([2, 5, 6, 8, 1, 1])

In [32]:
rand_array.argmin() #index of minimumvalue of random array

1

In [43]:
rand_array.argmax()  #index of maximumvalue of random array

3

In [44]:
rand_array.max()  #maximum value of random array

8

In [45]:
sample_array.max()

39

In [33]:
sample_array.dtype

dtype('int32')

In [36]:
a=np.random.rand(3,4)
a

array([[0.91754846, 0.6416107 , 0.83489079, 0.70709211],
       [0.86786489, 0.92302736, 0.59840798, 0.43318412],
       [0.61219581, 0.20907223, 0.57368302, 0.23172271]])

In [37]:
a.T  #Transpose of matrix

array([[0.91754846, 0.86786489, 0.61219581],
       [0.6416107 , 0.92302736, 0.20907223],
       [0.83489079, 0.59840798, 0.57368302],
       [0.70709211, 0.43318412, 0.23172271]])

In [ ]:
import numpy as np  #defines np as numpy instead of defining numpy in every line

In [49]:
sample_array= np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [50]:
sample_array=sample_array.reshape(3,6)  #displays all elements athat are reachable 3x6
sample_array

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27]])

In [51]:
sample_array=sample_array.reshape(2,9)  #displays all elements that are reachable 2x9
sample_array

array([[10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [52]:
sample_array= sample_array.reshape(3,4)  #will show error as there are 18 elements
sample_array

ValueError: cannot reshape array of size 18 into shape (3,4)

In [56]:
sample_array=sample_array.reshape(18,1)  #displays all elements athat are reachable 18x1
sample_array

array([[ 10],
       [100],
       [ 12],
       [ 13],
       [ 14],
       [ 15],
       [ 16],
       [ 17],
       [ 18],
       [ 19],
       [ 20],
       [ 21],
       [ 22],
       [ 23],
       [ 24],
       [ 25],
       [ 26],
       [ 27]])

In [53]:
sample_array=sample_array.reshape(1,18)  #displays all elements athat are reachable 1x18
sample_array

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
        26, 27]])

In [57]:
sample_array= np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [58]:
sample_array[1:12]  #takes index from 1 to 12 i.e 11 to 21

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [61]:
sample_array[:]=2001
sample_array

array([2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001,
       2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001,
       2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001,
       2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001,
       2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001,
       2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001,
       2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001,
       2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001, 2001,
       2001, 2001])

### Two-Dimensional array

In [62]:
import numpy as np

In [63]:
sample_matrix=np.array(([24,5,89,32],[45,78,10,8],[8,7,63,4]))
sample_matrix

array([[24,  5, 89, 32],
       [45, 78, 10,  8],
       [ 8,  7, 63,  4]])

In [64]:
sample_matrix[2][2]  #element no.2x2

63

In [65]:
sample_matrix[1][2]

10

In [67]:
sample_matrix[:,2] #entire rows and 3rd colummn

array([89, 10, 63])

In [68]:
sample_matrix[1,1]

78

In [69]:
sample_matrix[1:3, 2:4]  #1:3 means rows from index n to n-1 i.e row index 1,3-1=2; 
                         #2:4 menas column from index 2, 4-1=3, i.e 2,3 column

array([[10,  8],
       [63,  4]])

In [71]:
sample_matrix[:2,:3]  #from 0 to 2nd index row and from 0 to 2nd index column

array([[24,  5, 89],
       [45, 78, 10]])

In [72]:
sample_matrix[1:,2:]

array([[10,  8],
       [63,  4]])

In [73]:
sample_matrix[2]

array([ 8,  7, 63,  4])

In [75]:
sample_matrix[:,2]

array([89, 10, 63])

In [ ]:
 import numpy as np

In [78]:
sample_array=np.arange(1,21)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [79]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [80]:
np.exp(sample_array)  #exponential function

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08])

In [81]:
np.sqrt(sample_array)  #square root

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595])

In [82]:
np.log(sample_array) #natural log vale i,e ln with base e

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227])

In [83]:
np.max(sample_array)

20

In [84]:
np.min(sample_array)

1

In [85]:
np.argmin(sample_array)

0

In [86]:
np.argmax(sample_array)

19

In [87]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400], dtype=int32)

In [88]:
np.std(sample_array)

5.766281297335398

In [89]:
np.var(sample_array)

33.25

In [90]:
np.mean(sample_array)

10.5

In [95]:
array=np.random.randn(3,4)    ##normal distribution
array

array([[-1.68573257,  1.07711022,  1.01703081, -0.72015995],
       [ 0.61424499,  0.09667356,  0.19992104, -0.43264253],
       [ 0.75969441, -2.89408277,  0.65365799, -0.57267885]])

In [96]:
np.round(array,decimals=2)

array([[-1.69,  1.08,  1.02, -0.72],
       [ 0.61,  0.1 ,  0.2 , -0.43],
       [ 0.76, -2.89,  0.65, -0.57]])

In [98]:
sports=np.array(['golf','cricket','football','volley', 'cricket'])
np.unique(sports)

array(['cricket', 'football', 'golf', 'volley'], dtype='<U8')

# Thank you