# Pandas

In [5]:
import pandas as pd   #when we want to create multi-dimensional data i.e rows,columns
                      #we use pandas framework

In [47]:
labels=['a','b','c','d']
labels

['a', 'b', 'c', 'd']

In [45]:
list = [10,28,3,4]
list

[10, 28, 3, 4]

In [44]:
import numpy as np
array=np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [43]:
dict={'w':10,'x':20,'y':30,'z':40}
dict

{'w': 10, 'x': 20, 'y': 30, 'z': 40}

In [12]:
pd.Series(data=labels)   #  note: S should be capitals

0    a
1    b
2    c
3    d
dtype: object

In [48]:
pd.Series(data=list)

0    10
1    28
2     3
3     4
dtype: int64

In [49]:
pd.Series(data=list,index=labels)

a    10
b    28
c     3
d     4
dtype: int64

In [50]:
pd.Series(labels,list)  #first command becomes data values, second becomes index

10    a
28    b
3     c
4     d
dtype: object

In [51]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

In [ ]:
import pandas as pd

In [53]:
df=pd.read_csv("Ex-1 occupation.csv")
df

user_id|age|gender|occupation|zip_code
0                  1|24|M|technician|85711
1                       2|53|F|other|94043
2                      3|23|M|writer|32067
3                  4|24|M|technician|43537
4                       5|33|F|other|15213
..                                     ...
938                 939|26|F|student|33319
939           940|32|M|administrator|02215
940                 941|20|M|student|97229
941               942|48|F|librarian|78209
942                 943|22|M|student|77841

[943 rows x 1 columns]

### Pandas Dataframe and indexing

In [18]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [19]:
sports1['basketball']  #here basketball is index & data value is 3
                       # for slicing & indexing [ ] are used not parenthesis

3

In [23]:
sports2=pd.Series([11,13,12,4], index=['cricket','football','baseball','golf'])
sports2

cricket     11
football    13
baseball    12
golf         4
dtype: int64

In [24]:
sports1+ sports2 #while adding to dataframes both the datas should be present in each frame
                #  else it will show NaN (not a number)

baseball       NaN
basketball     NaN
cricket       12.0
football      15.0
golf           8.0
dtype: float64

In [27]:
import pandas as pd
import numpy as np

In [28]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(), columns='Score1 Score2 Score3 Score4 Score5'.split())
df1           #split() is used bcz we have to split the string "A B C D E F G H"
              #generates random values b/w 0 and 1 (uniform distribution)

Score1    Score2    Score3    Score4    Score5
A  0.388012  0.464448  0.404918  0.014974  0.170711
B  0.226508  0.502648  0.795855  0.424710  0.794433
C  0.147171  0.728927  0.331909  0.919542  0.769318
D  0.990108  0.293854  0.257299  0.768111  0.875412
E  0.500337  0.212273  0.633963  0.420917  0.145757
F  0.475957  0.297126  0.996309  0.536054  0.119029
G  0.186182  0.611233  0.175936  0.351825  0.204238
H  0.095448  0.266734  0.622901  0.550732  0.192560

In [30]:
df1[['Score2','Score1', 'Score5']]     #taking output

Score2    Score1    Score5
A  0.464448  0.388012  0.170711
B  0.502648  0.226508  0.794433
C  0.728927  0.147171  0.769318
D  0.293854  0.990108  0.875412
E  0.212273  0.500337  0.145757
F  0.297126  0.475957  0.119029
G  0.611233  0.186182  0.204238
H  0.266734  0.095448  0.192560

In [31]:
df1['Score6']=df1['Score1']-df1['Score2']   #add new column Score6
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.388012  0.464448  0.404918  0.014974  0.170711 -0.076436
B  0.226508  0.502648  0.795855  0.424710  0.794433 -0.276140
C  0.147171  0.728927  0.331909  0.919542  0.769318 -0.581756
D  0.990108  0.293854  0.257299  0.768111  0.875412  0.696253
E  0.500337  0.212273  0.633963  0.420917  0.145757  0.288064
F  0.475957  0.297126  0.996309  0.536054  0.119029  0.178831
G  0.186182  0.611233  0.175936  0.351825  0.204238 -0.425050
H  0.095448  0.266734  0.622901  0.550732  0.192560 -0.171286

In [33]:
df1.drop('Score5',axis=1)  
#drop a column Score5, axis=1 is index used for column & by defualt for row it is 0

Score1    Score2    Score3    Score4    Score6
A  0.388012  0.464448  0.404918  0.014974 -0.076436
B  0.226508  0.502648  0.795855  0.424710 -0.276140
C  0.147171  0.728927  0.331909  0.919542 -0.581756
D  0.990108  0.293854  0.257299  0.768111  0.696253
E  0.500337  0.212273  0.633963  0.420917  0.288064
F  0.475957  0.297126  0.996309  0.536054  0.178831
G  0.186182  0.611233  0.175936  0.351825 -0.425050
H  0.095448  0.266734  0.622901  0.550732 -0.171286

In [34]:
df1.drop("E", axis=0)
#removes row E , here axis =0 may or may not be used bcz it by default 0 for row

Score1    Score2    Score3    Score4    Score5    Score6
A  0.388012  0.464448  0.404918  0.014974  0.170711 -0.076436
B  0.226508  0.502648  0.795855  0.424710  0.794433 -0.276140
C  0.147171  0.728927  0.331909  0.919542  0.769318 -0.581756
D  0.990108  0.293854  0.257299  0.768111  0.875412  0.696253
F  0.475957  0.297126  0.996309  0.536054  0.119029  0.178831
G  0.186182  0.611233  0.175936  0.351825  0.204238 -0.425050
H  0.095448  0.266734  0.622901  0.550732  0.192560 -0.171286

In [35]:
df1.drop("E")
#removes row E , here axis =0 may or may not be used bcz it by default 0 for row

Score1    Score2    Score3    Score4    Score5    Score6
A  0.388012  0.464448  0.404918  0.014974  0.170711 -0.076436
B  0.226508  0.502648  0.795855  0.424710  0.794433 -0.276140
C  0.147171  0.728927  0.331909  0.919542  0.769318 -0.581756
D  0.990108  0.293854  0.257299  0.768111  0.875412  0.696253
F  0.475957  0.297126  0.996309  0.536054  0.119029  0.178831
G  0.186182  0.611233  0.175936  0.351825  0.204238 -0.425050
H  0.095448  0.266734  0.622901  0.550732  0.192560 -0.171286

In [37]:
df2={'ID':[101,102,103,127,169],'Name':['Jackinn', 'Mercy','Alish','kalvin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID     Name  Profit
0  101  Jackinn      20
1  102    Mercy      54
2  103    Alish      56
3  127   kalvin      87
4  169    Lally     123

Practice

1) Create a null vector of size 10

2) Create a null vector of size 10 but the fifth value should be one

3) Create a vector with values ranging from 10 to 25

4) Reverse the above vector

5) Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np

In [54]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
a=np.zeros(10)
a[4]=1; a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [69]:
z=np.arange(10,25)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [70]:
z[::-1]

array([24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [68]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


THANK YOU